# Generated by Django 4.1 on 2022-12-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=50, null=True)),
                ('propertyDescription', models.TextField(max_length=100, null=True)),
                ('propertyAddress', models.CharField(max_length=50, null=True)),
                ('propertyType', models.CharField(max_length=50, null=True)),
                ('propertyNeighborhood', models.CharField(max_length=50, null=True)),
                ('propertyZipCode', models.CharField(max_length=10, null=True)),
                ('propertyPrice', models.CharField(max_length=10, null=True)),
                ('propertyStatus', models.CharField(max_length=15, null=True)),
                ('featuredProperty', models.BooleanField(default=False)),
                ('propertyImage1', models.ImageField(default='default.jpg', upload_to='listings_pics')),
                ('propertyImage2', models.ImageField(default='default.jpg', upload_to='listings_pics')),
                ('propertyImage3', models.ImageField(default='default.jpg', upload_to='listings_pics')),
                ('propertyImage4', models.ImageField(default='default.jpg', upload_to='listings_pics')),
            ],
        ),
        migrations.CreateModel(
            name='realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
